$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

type: object

properties:
  output_folder:
    type: string
  reads_folder:
    type: string
  reads_identifier:
    type: string
  silva_nr_train_set:
    type: string
  dada2:
    type: object
    properties:
      truncLen:
        type: array
        items:
          type: integer
    required:
      - truncLen

required:
      - reads_folder
      - reads_identifier
      - output_folder
      - silva_nr_train_set
      - dada2